# Generated by Django 2.1.5 on 2019-02-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('age', models.IntegerField()),
                ('address', models.ManyToManyField(to='hotelapp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('costToBusiness', models.IntegerField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('Hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Hotel')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vegDishPrice', models.IntegerField()),
                ('nonVegDishPrice', models.IntegerField()),
                ('chineseDishPrice', models.IntegerField()),
                ('dessertPrice', models.IntegerField()),
                ('starterPrice', models.IntegerField()),
                ('hotel', models.ManyToManyField(to='hotelapp.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('aadharNo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('category', models.TextField(max_length=100)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Address')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Waiter'),
        ),
    ]
