# Generated by Django 2.1.5 on 2019-02-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(related_name='address', to='hotelapp.Address'),
        ),
    ]
